// Catalog modelled on thevitacare.com (THEVITACARE, Surat, Gujarat – ships to USA).
// Prices are in USD, as listed on the original store.

export const seedCategories = [
  { name: "Supplements", slug: "supplements", description: "Generic pharmaceutical tablets and health supplements sourced from licensed Indian manufacturers.", image: "/images/tabs-white-blister.jpg" },
  { name: "Skin Care", slug: "skin-care", description: "Hydration, anti-aging and acne care essentials.", image: "/images/skincare-set.jpg" },
  { name: "Serum", slug: "serum", description: "Concentrated actives for targeted skin concerns.", image: "/images/serum-amber.jpg" },
  { name: "Sunscreens", slug: "sunscreens", description: "Broad-spectrum daily sun protection.", image: "/images/sunscreen-spf50.jpg" },
  { name: "Eye Cream", slug: "eye-cream", description: "Brighten and de-puff the delicate under-eye area.", image: "/images/cream-jar.jpg" },
  { name: "Face Wash", slug: "face-wash", description: "Gentle daily cleansers for every skin type.", image: "/images/face-wash.jpg" },
  { name: "Hair Care", slug: "hair-care", description: "Nourishing oils and treatments for stronger hair.", image: "/images/hair-oil.jpg" },
  { name: "Hair Color", slug: "hair-color", description: "Ammonia-free, long-lasting hair colour.", image: "/images/hair-elixir.jpg" },
  { name: "Lip Care", slug: "lip-care", description: "Balms and treatments for soft, healthy lips.", image: "/images/cream-jars.jpg" },
  { name: "Lipsticks", slug: "lipsticks", description: "Rich, long-wear colour.", image: "/images/lipsticks.jpg" },
  { name: "Tools & Accessories", slug: "tools-accessories", description: "Beauty tools and personal care accessories.", image: "/images/makeup-tools.jpg" },
];

const rxNote =
  "This is a prescription medicine. Use only under the guidance of a licensed healthcare professional. Do not exceed the prescribed dose. Keep out of reach of children. Store below 25°C, protected from light and moisture.";

type Seed = {
  name: string; slug: string; category: string; brand?: string; sku?: string;
  shortDescription: string; description: string; benefits: string[]; ingredients?: string; dosage?: string;
  price: string; salePrice?: string | null; variants?: { label: string; price: number }[];
  image: string; rating: string; reviewCount: number; featured: boolean; form: string; servings: number;
};

const ivermectin = (strength: string, slug: string, packs: { label: string; price: number }[], img: string, featured = false, brand = "Ivera"): Seed => ({
  name: `${brand} Ivermectin${brand === "Ivera" ? "s" : ""} ${strength} Tablet/s`,
  slug,
  category: "supplements",
  brand,
  sku: `${brand.toUpperCase()}${strength.toUpperCase()}`,
  shortDescription: `${brand} ${strength} contains Ivermectin ${strength}, a broad-spectrum anthelmintic used to treat parasitic infections such as strongyloidiasis, onchocerciasis and scabies.`,
  description: `${brand} ${strength} Tablet is an anti-parasitic medicine containing Ivermectin ${strength}. It works by binding to glutamate-gated chloride channels in the nerve and muscle cells of parasites, causing paralysis and death of the parasite. It is prescribed for intestinal strongyloidiasis, onchocerciasis (river blindness), scabies, head lice and certain other parasitic worm infections. Manufactured in India in WHO-GMP certified facilities. Sold in strips of 10 tablets.`,
  benefits: ["Broad-spectrum anti-parasitic", "Single-dose regimens for many indications", "WHO-GMP certified manufacturing", "Blister packed for freshness"],
  ingredients: `Each uncoated tablet contains Ivermectin IP ${strength}. Excipients: microcrystalline cellulose, pregelatinised starch, magnesium stearate, butylated hydroxyanisole, citric acid.`,
  dosage: `Take on an empty stomach with a full glass of water, exactly as prescribed by your doctor. Dose is based on body weight and the condition being treated. ${rxNote}`,
  price: String(packs[packs.length - 1].price),
  salePrice: null,
  variants: packs,
  image: img,
  rating: "4.7",
  reviewCount: Math.floor(Math.random() * 60) + 12,
  featured,
  form: "Tablets",
  servings: 10,
});

export const seedProducts: Seed[] = [
  // ---- Supplements (as listed on thevitacare.com, USD) ----
  ivermectin("3mg", "ivera-ivermectins-3mg-tablet-s", [{ label: "100 Tablets", price: 163.2 }], "/images/tabs-white-blister.jpg"),
  ivermectin("6mg", "ivera-ivermectins-6mg-tablet-s", [{ label: "100 Tablets", price: 230 }], "/images/tabs-hand-blister.jpg", true),
  ivermectin("12mg", "ivera-ivermectins-12mg-tablet-s", [{ label: "30 Tablets", price: 65 }, { label: "100 Tablets", price: 180 }], "/images/tabs-silver-blister.jpg", true),
  ivermectin("20mg", "ivera-ivermectins-20mg-tablet-s", [{ label: "30 Tablets", price: 90 }, { label: "100 Tablets", price: 250 }], "/images/tabs-assorted.jpg", true),
  ivermectin("24mg", "ivera-ivermectins-24mg-tablet-s", [{ label: "50 Tablets", price: 160 }, { label: "100 Tablets", price: 270 }], "/images/tabs-black.jpg", true),
  ivermectin("6mg", "iverheal-6-mg", [{ label: "30 Tablets", price: 69 }], "/images/tabs-yellow.jpg", false, "Iverheal"),
  ivermectin("12mg", "iverheal-12-mg", [{ label: "30 Tablets", price: 85 }], "/images/tabs-pink.jpg", false, "Iverheal"),
  ivermectin("6mg", "iverclear-6-mg", [{ label: "50 Tablets", price: 110 }], "/images/tabs-white-blister.jpg", false, "Iverclear"),
  ivermectin("12mg", "iverjohn-12-mg", [{ label: "100 Tablets", price: 290 }], "/images/tabs-silver-blister.jpg", true, "Iverjohn"),
  {
    name: "Niclosamide 500 mg",
    slug: "niclosamide-500-mg",
    category: "supplements",
    brand: "Niclosamide",
    sku: "NICLO500",
    shortDescription: "Niclosamide 500mg chewable tablets – an anthelmintic used for tapeworm infections (taeniasis, diphyllobothriasis, hymenolepiasis).",
    description: "Niclosamide 500 mg is an anti-tapeworm medicine. It works by inhibiting oxidative phosphorylation and glucose uptake in the tapeworm, causing it to detach and be expelled. It is minimally absorbed from the gut, acting locally in the intestine. Supplied in strips of 4 chewable tablets.",
    benefits: ["Effective against beef, pork, fish and dwarf tapeworm", "Acts locally in the intestine", "Chewable tablets", "WHO essential medicine"],
    ingredients: "Each chewable tablet contains Niclosamide IP 500 mg.",
    dosage: `Chew tablets thoroughly and swallow with a little water after a light meal, as directed by your doctor. ${rxNote}`,
    price: "39.60", salePrice: null, variants: [{ label: "20 Tablets", price: 39.6 }, { label: "60 Tablets", price: 99 }],
    image: "/images/tabs-yellow.jpg", rating: "4.6", reviewCount: 23, featured: false, form: "Chewable Tablets", servings: 4,
  },
  {
    name: "Fenben FBD 500 mg",
    slug: "fenben-fbd-500-mg",
    category: "supplements",
    brand: "Fenben",
    sku: "FENBEN500",
    shortDescription: "Fenbendazole 500mg tablets – a broad-spectrum benzimidazole anthelmintic.",
    description: "Fenben FBD 500 mg contains Fenbendazole, a benzimidazole-class anthelmintic that disrupts microtubule formation in parasites, blocking glucose uptake and leading to parasite death. It is effective against roundworms, hookworms, whipworms and certain tapeworms. Supplied in strips of 10 tablets.",
    benefits: ["Broad-spectrum benzimidazole anthelmintic", "Well tolerated", "Convenient once-daily dosing", "Blister packed"],
    ingredients: "Each tablet contains Fenbendazole 500 mg.",
    dosage: `Use strictly as directed by a qualified healthcare professional. ${rxNote}`,
    price: "160", salePrice: null, variants: [{ label: "100 Tablets", price: 160 }, { label: "200 Tablets", price: 280 }],
    image: "/images/tabs-pink.jpg", rating: "4.8", reviewCount: 57, featured: true, form: "Tablets", servings: 10,
  },
  {
    name: "Rifaximine Healing 550 Tabs",
    slug: "rifaximine-healing-550-tabs",
    category: "supplements",
    brand: "Healing",
    sku: "RIFAX550H",
    shortDescription: "Rifaximin 550mg – gut-selective antibiotic for IBS-D, traveler's diarrhoea and hepatic encephalopathy.",
    description: "Rifaximine Healing 550 contains Rifaximin, a non-absorbable rifamycin antibiotic that acts locally in the gastrointestinal tract. It is prescribed to reduce the recurrence of hepatic encephalopathy, treat irritable bowel syndrome with diarrhoea (IBS-D), and treat traveler's diarrhoea caused by non-invasive E. coli. Because less than 1% is absorbed systemically, side effects are minimal.",
    benefits: ["Gut-selective – minimal systemic absorption", "Reduces recurrence of hepatic encephalopathy", "Relieves IBS-D symptoms", "Treats traveler's diarrhoea"],
    ingredients: "Each film-coated tablet contains Rifaximin 550 mg.",
    dosage: `Typically 550 mg twice or three times daily depending on indication, as prescribed. May be taken with or without food. ${rxNote}`,
    price: "90", salePrice: null, variants: [{ label: "30 Tablets", price: 90 }, { label: "60 Tablets", price: 160 }],
    image: "/images/tabs-white-blister.jpg", rating: "4.9", reviewCount: 88, featured: true, form: "Tablets", servings: 10,
  },
  {
    name: "Xifaxan 550 mg Tabs",
    slug: "xifaxan-550-mg-tabs",
    category: "supplements",
    brand: "Xifaxan",
    sku: "XIFAX550",
    shortDescription: "Rifaximin 550mg tablets for hepatic encephalopathy, IBS-D and traveler's diarrhoea.",
    description: "Xifaxan 550 mg (Rifaximin) is a broad-spectrum, poorly absorbed oral antibiotic that targets bacteria in the gut. It is used to reduce the risk of overt hepatic encephalopathy recurrence in adults, treat IBS-D, and treat traveler's diarrhoea. Supplied in strips of 10 film-coated tablets.",
    benefits: ["Locally acting gut antibiotic", "Proven in IBS-D & hepatic encephalopathy", "Low risk of systemic side effects", "Film-coated, easy to swallow"],
    ingredients: "Each film-coated tablet contains Rifaximin 550 mg.",
    dosage: `As prescribed by your physician – commonly 550 mg twice daily (HE) or three times daily for 14 days (IBS-D). ${rxNote}`,
    price: "90", salePrice: null, variants: [{ label: "30 Tablets", price: 90 }, { label: "60 Tablets", price: 160 }],
    image: "/images/tabs-silver-blister.jpg", rating: "4.8", reviewCount: 64, featured: true, form: "Tablets", servings: 10,
  },
  {
    name: "Rifaximine 400 mg Tabs",
    slug: "rifaximine-400-mg-tabs",
    category: "supplements",
    brand: "Rifaximine",
    sku: "RIFAX400",
    shortDescription: "Rifaximin 400mg tablets – for traveler's diarrhoea, SIBO and hepatic encephalopathy.",
    description: "Rifaximine 400 mg contains Rifaximin, a semi-synthetic rifamycin antibiotic with negligible systemic absorption. The 400 mg strength is commonly prescribed for traveler's diarrhoea, small intestinal bacterial overgrowth (SIBO) and hepatic encephalopathy. Supplied in strips of 10 tablets.",
    benefits: ["Effective for SIBO and traveler's diarrhoea", "Minimal systemic absorption", "Generally well tolerated", "Manufactured to WHO-GMP standards"],
    ingredients: "Each film-coated tablet contains Rifaximin 400 mg.",
    dosage: `Commonly 400 mg three times daily for 7–14 days, as prescribed. ${rxNote}`,
    price: "75", salePrice: null, variants: [{ label: "30 Tablets", price: 75 }, { label: "60 Tablets", price: 140 }],
    image: "/images/tabs-hand-blister.jpg", rating: "4.7", reviewCount: 41, featured: false, form: "Tablets", servings: 10,
  },
  {
    name: "Augumentine 1g Duo",
    slug: "augumentine-1g-duo",
    category: "supplements",
    brand: "Augumentine",
    sku: "AUGDUO1G",
    shortDescription: "Amoxicillin 875mg + Clavulanic Acid 125mg – broad-spectrum antibiotic for bacterial infections.",
    description: "Augumentine 1g Duo combines Amoxicillin (a penicillin-class antibiotic) with Clavulanic Acid (a beta-lactamase inhibitor) to treat a wide range of bacterial infections including sinusitis, otitis media, lower respiratory tract infections, urinary tract infections, and skin and soft tissue infections. Clavulanic acid protects amoxicillin from being broken down by resistant bacteria.",
    benefits: ["Broad-spectrum coverage", "Overcomes beta-lactamase resistance", "Twice-daily dosing", "Film-coated tablets"],
    ingredients: "Each film-coated tablet contains Amoxicillin Trihydrate IP eq. to Amoxicillin 875 mg and Potassium Clavulanate Diluted IP eq. to Clavulanic Acid 125 mg.",
    dosage: `Usually one tablet every 12 hours at the start of a meal, for the duration prescribed. Complete the full course. ${rxNote}`,
    price: "190", salePrice: null, variants: [{ label: "60 Tablets", price: 190 }],
    image: "/images/tabs-assorted.jpg", rating: "4.6", reviewCount: 35, featured: true, form: "Tablets", servings: 6,
  },
  {
    name: "Multivitamin & Mineral Capsules",
    slug: "multivitamin-mineral-capsules",
    category: "supplements",
    brand: "The Vita Care",
    sku: "MVM60",
    shortDescription: "Daily multivitamin with 24 essential vitamins & minerals for energy and immunity.",
    description: "A complete daily multivitamin and mineral formula to fill nutritional gaps, support energy metabolism, immune function and overall wellbeing. Contains Vitamin A, C, D3, E, B-complex, Zinc, Iron, Magnesium and Selenium.",
    benefits: ["Fills daily nutritional gaps", "Supports energy & immunity", "Once-daily convenience", "No artificial colours"],
    ingredients: "Vitamin A, C, D3, E, K, B1, B2, B3, B5, B6, B7, B9, B12, Calcium, Iron, Magnesium, Zinc, Selenium, Copper, Manganese, Chromium, Iodine.",
    dosage: "Take one capsule daily with food.",
    price: "29", salePrice: "24", variants: [{ label: "60 Capsules", price: 24 }],
    image: "/images/caps-white-bottle.jpg", rating: "4.5", reviewCount: 19, featured: false, form: "Capsules", servings: 60,
  },
  {
    name: "Omega-3 Fish Oil 1000 mg Softgels",
    slug: "omega-3-fish-oil-1000mg-softgels",
    category: "supplements",
    brand: "The Vita Care",
    sku: "OMG1000",
    shortDescription: "Triple strength Omega-3 with EPA & DHA for heart, brain and joint health.",
    description: "Molecularly distilled fish oil delivering 360 mg EPA and 240 mg DHA per softgel. Supports cardiovascular health, cognitive function and joint flexibility. Mercury tested and burpless.",
    benefits: ["Supports heart health", "Sharpens memory & focus", "Reduces joint stiffness", "Mercury-free"],
    ingredients: "Fish Oil 1000 mg (EPA 360 mg, DHA 240 mg), Gelatin, Glycerin, Vitamin E.",
    dosage: "Take 1–2 softgels daily with meals.",
    price: "32", salePrice: "26", variants: [{ label: "60 Softgels", price: 26 }, { label: "120 Softgels", price: 45 }],
    image: "/images/supp-bottles.jpg", rating: "4.7", reviewCount: 28, featured: false, form: "Softgels", servings: 60,
  },
  {
    name: "Vitamin C 1000 mg Gummies",
    slug: "vitamin-c-1000mg-gummies",
    category: "supplements",
    brand: "The Vita Care",
    sku: "VITC1000",
    shortDescription: "Orange-flavoured gummies with 1000 mg Vitamin C plus Zinc for immune support.",
    description: "Delicious chewable gummies delivering a high-potency dose of Vitamin C along with Zinc to support immune function, collagen production and antioxidant defence. Gelatin-free and vegan friendly.",
    benefits: ["Supports immune function", "Antioxidant protection", "Promotes collagen & skin health", "Vegan, no artificial colours"],
    ingredients: "Vitamin C 1000 mg, Zinc 10 mg, Pectin, Natural Orange Flavour, Citric Acid, Cane Sugar.",
    dosage: "Take 2 gummies daily.",
    price: "22", salePrice: "18", variants: [{ label: "60 Gummies", price: 18 }],
    image: "/images/pills-jar.jpg", rating: "4.8", reviewCount: 46, featured: false, form: "Gummies", servings: 30,
  },
  {
    name: "Probiotic 50 Billion CFU Capsules",
    slug: "probiotic-50-billion-cfu-capsules",
    category: "supplements",
    brand: "The Vita Care",
    sku: "PROB50B",
    shortDescription: "15 probiotic strains with prebiotic fibre for gut health, digestion and immunity.",
    description: "A powerful blend of 15 Lactobacillus and Bifidobacterium strains delivering 50 billion live cultures per delayed-release capsule, plus inulin prebiotic to feed beneficial bacteria. Shelf stable.",
    benefits: ["Improves digestion & reduces bloating", "Supports immunity", "Delayed-release capsules", "No refrigeration needed"],
    ingredients: "Probiotic Blend 50 Billion CFU, Inulin 100 mg, Vegetable Capsule.",
    dosage: "Take 1 capsule daily on an empty stomach.",
    price: "34", salePrice: "28", variants: [{ label: "30 Capsules", price: 28 }],
    image: "/images/caps-jar.jpg", rating: "4.7", reviewCount: 31, featured: false, form: "Capsules", servings: 30,
  },
  {
    name: "Turmeric Curcumin 95% with BioPerine",
    slug: "turmeric-curcumin-bioperine",
    category: "supplements",
    brand: "The Vita Care",
    sku: "TURM95",
    shortDescription: "1000 mg Turmeric Curcumin (95% curcuminoids) with black pepper extract for joint support.",
    description: "Standardised turmeric root extract enhanced with BioPerine® black pepper extract for up to 2000% better absorption. Supports joint mobility, a healthy inflammatory response and antioxidant defence.",
    benefits: ["Reduces joint pain & stiffness", "Powerful antioxidant", "Supports liver & digestion", "Enhanced absorption"],
    ingredients: "Turmeric Root Extract (95% Curcuminoids) 1000 mg, BioPerine® 10 mg, Vegetable Capsule.",
    dosage: "Take 2 capsules daily with food.",
    price: "26", salePrice: "21", variants: [{ label: "60 Capsules", price: 21 }],
    image: "/images/caps-pink.jpg", rating: "4.6", reviewCount: 22, featured: false, form: "Capsules", servings: 60,
  },

  // ---- Skin & personal care (1 product per category, as on the original store; 4 in Skin Care) ----
  {
    name: "Hyaluronic Acid Hydrating Moisturiser 50 g",
    slug: "hyaluronic-acid-hydrating-moisturiser",
    category: "skin-care", brand: "The Vita Care", sku: "SKHA50",
    shortDescription: "Lightweight, oil-free daily moisturiser with 2% Hyaluronic Acid and Ceramides for 72-hour hydration.",
    description: "A fast-absorbing gel-cream that locks in moisture with multi-weight Hyaluronic Acid and strengthens the skin barrier with Ceramides and Niacinamide. Non-comedogenic, fragrance-free and suitable for all skin types including sensitive skin.",
    benefits: ["72-hour hydration", "Strengthens skin barrier", "Non-comedogenic & fragrance-free", "Suitable for sensitive skin"],
    ingredients: "Aqua, Glycerin, Sodium Hyaluronate, Niacinamide, Ceramide NP, Squalane, Panthenol, Allantoin, Carbomer, Phenoxyethanol.",
    dosage: "Apply to clean face and neck morning and night.",
    price: "24", salePrice: "19", variants: [{ label: "50 g", price: 19 }],
    image: "/images/cream-jars.jpg", rating: "4.7", reviewCount: 52, featured: true, form: "Cream", servings: 50,
  },
  {
    name: "Retinol 0.3% Night Cream 30 g",
    slug: "retinol-night-cream",
    category: "skin-care", brand: "The Vita Care", sku: "SKRET30",
    shortDescription: "Encapsulated Retinol night cream to reduce fine lines, wrinkles and uneven texture.",
    description: "A gentle yet effective anti-aging night cream with 0.3% encapsulated Retinol, Peptides and Vitamin E. Boosts cell turnover and collagen production for smoother, firmer, more even-toned skin with minimal irritation.",
    benefits: ["Reduces fine lines & wrinkles", "Improves skin texture", "Encapsulated for low irritation", "Dermatologist tested"],
    ingredients: "Aqua, Caprylic/Capric Triglyceride, Glycerin, Retinol, Palmitoyl Tripeptide-1, Tocopheryl Acetate, Shea Butter, Bisabolol.",
    dosage: "Apply a pea-sized amount at night on cleansed skin. Use sunscreen during the day.",
    price: "32", salePrice: "27", variants: [{ label: "30 g", price: 27 }],
    image: "/images/cream-jar.jpg", rating: "4.6", reviewCount: 37, featured: false, form: "Cream", servings: 30,
  },
  {
    name: "Salicylic Acid 2% Acne Control Gel 30 g",
    slug: "salicylic-acid-acne-gel",
    category: "skin-care", brand: "The Vita Care", sku: "SKSAL30",
    shortDescription: "Oil-free spot treatment gel with 2% Salicylic Acid and Tea Tree to clear acne and unclog pores.",
    description: "A targeted acne control gel that penetrates pores to dissolve excess oil and dead skin. With Salicylic Acid, Tea Tree Oil and Zinc PCA to reduce breakouts, blackheads and redness without over-drying.",
    benefits: ["Clears acne & blackheads", "Controls excess oil", "Reduces redness", "Non-drying formula"],
    ingredients: "Aqua, Salicylic Acid 2%, Melaleuca Alternifolia Leaf Oil, Zinc PCA, Niacinamide, Aloe Barbadensis Leaf Juice, Carbomer.",
    dosage: "Apply a thin layer to affected areas 1–2 times daily.",
    price: "18", salePrice: "15", variants: [{ label: "30 g", price: 15 }],
    image: "/images/skincare-set.jpg", rating: "4.5", reviewCount: 44, featured: false, form: "Gel", servings: 30,
  },
  {
    name: "Niacinamide 10% + Zinc Toner 150 ml",
    slug: "niacinamide-zinc-toner",
    category: "skin-care", brand: "The Vita Care", sku: "SKNIA150",
    shortDescription: "Alcohol-free toner with 10% Niacinamide and 1% Zinc to minimise pores and even skin tone.",
    description: "A refreshing, alcohol-free toner that balances oil production, tightens the look of pores and fades dark spots. Niacinamide strengthens the skin barrier while Zinc soothes and controls shine.",
    benefits: ["Minimises pores", "Evens skin tone", "Controls shine", "Alcohol-free"],
    ingredients: "Aqua, Niacinamide, Zinc PCA, Glycerin, Sodium Hyaluronate, Panthenol, Centella Asiatica Extract.",
    dosage: "After cleansing, apply with a cotton pad or pat onto skin morning and night.",
    price: "16", salePrice: null, variants: [{ label: "150 ml", price: 16 }],
    image: "/images/skincare-bottles.jpg", rating: "4.6", reviewCount: 29, featured: false, form: "Toner", servings: 150,
  },
  {
    name: "Vitamin C 20% Brightening Face Serum 30 ml",
    slug: "vitamin-c-brightening-face-serum",
    category: "serum", brand: "The Vita Care", sku: "SRVC30",
    shortDescription: "Potent 20% Vitamin C serum with Ferulic Acid and Vitamin E for radiant, even-toned skin.",
    description: "A stable, high-potency Vitamin C (Ethyl Ascorbic Acid) serum boosted with Ferulic Acid and Vitamin E. Brightens dull skin, fades dark spots and pigmentation, boosts collagen and defends against environmental damage.",
    benefits: ["Brightens & evens tone", "Fades dark spots", "Boosts collagen", "Antioxidant defence"],
    ingredients: "Aqua, 3-O-Ethyl Ascorbic Acid 20%, Ferulic Acid, Tocopherol, Sodium Hyaluronate, Glycerin, Propanediol.",
    dosage: "Apply 3–4 drops to clean face every morning before moisturiser and sunscreen.",
    price: "28", salePrice: "22", variants: [{ label: "30 ml", price: 22 }],
    image: "/images/serum-amber.jpg", rating: "4.8", reviewCount: 73, featured: true, form: "Serum", servings: 30,
  },
  {
    name: "Ultra Light SPF 50+ PA++++ Sunscreen 50 ml",
    slug: "ultra-light-spf-50-sunscreen",
    category: "sunscreens", brand: "The Vita Care", sku: "SSSPF50",
    shortDescription: "Broad-spectrum SPF 50+ PA++++ sunscreen – lightweight, no white cast, water resistant.",
    description: "A silky, fast-absorbing sunscreen offering broad-spectrum UVA/UVB protection. Enriched with Vitamin E and Hyaluronic Acid, it leaves no white cast, doesn't feel greasy and works under makeup. Water resistant up to 80 minutes.",
    benefits: ["SPF 50+ PA++++ protection", "No white cast", "Non-greasy, matte finish", "Water resistant 80 min"],
    ingredients: "Aqua, Homosalate, Octocrylene, Ethylhexyl Salicylate, Butyl Methoxydibenzoylmethane, Titanium Dioxide, Tocopheryl Acetate, Sodium Hyaluronate.",
    dosage: "Apply generously 15 minutes before sun exposure. Reapply every 2 hours.",
    price: "20", salePrice: "16", variants: [{ label: "50 ml", price: 16 }],
    image: "/images/sunscreen-spf50.jpg", rating: "4.7", reviewCount: 61, featured: true, form: "Lotion", servings: 50,
  },
  {
    name: "Caffeine & Peptide Under Eye Cream 15 g",
    slug: "caffeine-peptide-under-eye-cream",
    category: "eye-cream", brand: "The Vita Care", sku: "EYCAF15",
    shortDescription: "Depuffing, brightening eye cream with Caffeine, Peptides and Vitamin K for dark circles.",
    description: "A cooling eye cream that reduces puffiness, dark circles and fine lines. Caffeine constricts blood vessels to reduce swelling, Peptides firm the skin and Vitamin K helps fade discolouration. Ophthalmologist tested.",
    benefits: ["Reduces puffiness", "Fades dark circles", "Smooths fine lines", "Ophthalmologist tested"],
    ingredients: "Aqua, Caffeine, Acetyl Hexapeptide-8, Phytonadione, Sodium Hyaluronate, Shea Butter, Cucumber Extract.",
    dosage: "Gently pat a small amount around the eye area morning and night.",
    price: "22", salePrice: "18", variants: [{ label: "15 g", price: 18 }],
    image: "/images/cream-jar.jpg", rating: "4.5", reviewCount: 26, featured: false, form: "Cream", servings: 15,
  },
  {
    name: "Gentle Foaming Face Wash 150 ml",
    slug: "gentle-foaming-face-wash",
    category: "face-wash", brand: "The Vita Care", sku: "FWGEN150",
    shortDescription: "Soap-free, pH-balanced foaming cleanser with Aloe and Green Tea for all skin types.",
    description: "A gentle, sulphate-free foaming face wash that removes dirt, oil and makeup without stripping the skin. Aloe Vera soothes, Green Tea provides antioxidants and Glycerin keeps skin hydrated and soft.",
    benefits: ["Sulphate & soap free", "pH balanced", "Removes makeup & oil", "Soothes with Aloe"],
    ingredients: "Aqua, Cocamidopropyl Betaine, Decyl Glucoside, Glycerin, Aloe Barbadensis Leaf Juice, Camellia Sinensis Leaf Extract, Panthenol.",
    dosage: "Massage onto damp face, rinse thoroughly. Use morning and night.",
    price: "14", salePrice: "11", variants: [{ label: "150 ml", price: 11 }],
    image: "/images/face-wash.jpg", rating: "4.6", reviewCount: 39, featured: false, form: "Cleanser", servings: 150,
  },
  {
    name: "Onion & Black Seed Hair Growth Oil 200 ml",
    slug: "onion-black-seed-hair-oil",
    category: "hair-care", brand: "The Vita Care", sku: "HCON200",
    shortDescription: "Red onion and black seed hair oil with 14 natural oils to reduce hair fall and boost growth.",
    description: "A nourishing blend of Red Onion Extract, Black Seed (Kalonji), Bhringraj, Amla, Castor and Argan oils. Strengthens roots, reduces hair fall, controls dandruff and promotes thicker, shinier hair. No mineral oil, silicones or parabens.",
    benefits: ["Reduces hair fall", "Promotes new growth", "Controls dandruff", "No mineral oil or silicones"],
    ingredients: "Allium Cepa Bulb Extract, Nigella Sativa Seed Oil, Eclipta Alba Extract, Emblica Officinalis, Ricinus Communis Seed Oil, Argania Spinosa Kernel Oil, Cocos Nucifera Oil.",
    dosage: "Massage into scalp, leave for at least 1 hour or overnight, then shampoo. Use 2–3 times a week.",
    price: "18", salePrice: "14", variants: [{ label: "200 ml", price: 14 }],
    image: "/images/hair-oil.jpg", rating: "4.6", reviewCount: 58, featured: false, form: "Oil", servings: 200,
  },
  {
    name: "Ammonia-Free Crème Hair Colour – Natural Black 1.0",
    slug: "ammonia-free-hair-colour-natural-black",
    category: "hair-color", brand: "The Vita Care", sku: "HCOL10",
    shortDescription: "Long-lasting, ammonia-free permanent hair colour with Argan oil for 100% grey coverage.",
    description: "A gentle permanent crème colour enriched with Argan Oil and Keratin. Delivers rich, natural-looking colour with 100% grey coverage and lasts up to 8 weeks – without ammonia. Kit includes colourant, developer, gloves and conditioner.",
    benefits: ["100% grey coverage", "Ammonia free", "Lasts up to 8 weeks", "Enriched with Argan & Keratin"],
    ingredients: "Colourant: Aqua, Cetearyl Alcohol, Ethanolamine, p-Phenylenediamine, Argania Spinosa Kernel Oil. Developer: Aqua, Hydrogen Peroxide 6%.",
    dosage: "Perform a patch test 48 hours before use. Mix colourant and developer, apply to dry hair, leave 30 minutes, rinse.",
    price: "12", salePrice: null, variants: [{ label: "Kit (60 ml + 60 ml)", price: 12 }],
    image: "/images/hair-elixir.jpg", rating: "4.4", reviewCount: 21, featured: false, form: "Crème", servings: 1,
  },
  {
    name: "Overnight Lip Sleeping Mask – Berry 10 g",
    slug: "overnight-lip-sleeping-mask-berry",
    category: "lip-care", brand: "The Vita Care", sku: "LCBER10",
    shortDescription: "Intensive overnight lip treatment with Shea Butter, Vitamin C and Berry extracts.",
    description: "A rich, melt-in lip mask that deeply hydrates and repairs dry, chapped lips while you sleep. Shea Butter and Murumuru Butter nourish, Hyaluronic Acid plumps and Vitamin C brightens. Wake up to soft, smooth, supple lips.",
    benefits: ["Repairs dry, chapped lips", "Plumps & smooths", "Brightens lip tone", "Delicious berry scent"],
    ingredients: "Diisostearyl Malate, Butyrospermum Parkii Butter, Astrocaryum Murumuru Seed Butter, Sodium Hyaluronate, Ascorbyl Palmitate, Rubus Idaeus Fruit Extract.",
    dosage: "Apply a generous layer to lips before bed. Can also be used as a daytime balm.",
    price: "12", salePrice: "9", variants: [{ label: "10 g", price: 9 }],
    image: "/images/cream-jars.jpg", rating: "4.7", reviewCount: 48, featured: false, form: "Balm", servings: 10,
  },
  {
    name: "Velvet Matte Liquid Lipstick – Classic Red",
    slug: "velvet-matte-liquid-lipstick-classic-red",
    category: "lipsticks", brand: "The Vita Care", sku: "LSRED01",
    shortDescription: "Transfer-proof, 12-hour matte liquid lipstick in a timeless classic red.",
    description: "A weightless, highly pigmented liquid lipstick that glides on smoothly and sets to a comfortable velvet-matte finish. Infused with Vitamin E and Jojoba Oil so lips stay soft, not dry. Transfer-proof and long-wearing up to 12 hours.",
    benefits: ["12-hour wear", "Transfer proof", "Non-drying formula", "One-swipe full coverage"],
    ingredients: "Isododecane, Dimethicone, Trimethylsiloxysilicate, Simmondsia Chinensis Seed Oil, Tocopheryl Acetate, CI 15850, CI 77491.",
    dosage: "Apply from the centre of lips outward. Allow 60 seconds to set.",
    price: "14", salePrice: "11", variants: [{ label: "Classic Red", price: 11 }, { label: "Nude Rose", price: 11 }, { label: "Berry Wine", price: 11 }],
    image: "/images/lipsticks.jpg", rating: "4.6", reviewCount: 67, featured: true, form: "Liquid Lipstick", servings: 1,
  },
  {
    name: "Professional Makeup Brush Set – 12 Piece",
    slug: "professional-makeup-brush-set-12",
    category: "tools-accessories", brand: "The Vita Care", sku: "TAMB12",
    shortDescription: "12-piece vegan synthetic brush set for face and eyes with travel pouch.",
    description: "Everything you need for a flawless application. Ultra-soft, cruelty-free synthetic bristles with ergonomic wooden handles. Includes foundation, powder, blush, contour, highlighter, and 7 eye brushes in a premium travel pouch.",
    benefits: ["12 essential brushes", "Vegan & cruelty free", "Ultra-soft synthetic bristles", "Travel pouch included"],
    ingredients: "Synthetic taklon bristles, aluminium ferrule, wooden handle, PU leather pouch.",
    dosage: "Clean brushes weekly with a gentle cleanser and air dry flat.",
    price: "25", salePrice: "19", variants: [{ label: "12 Piece Set", price: 19 }],
    image: "/images/makeup-tools.jpg", rating: "4.7", reviewCount: 83, featured: false, form: "Set", servings: 12,
  },
];
